stages:
  - lint
  - test

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - $HOME/.cache/pip

before_script:
  - pip install tox

lint:
  stage: lint
  image: python:3.6
  script: tox -e lint

test_python36:
  stage: test
  image: python:3.6
  script: tox -e 'py36-django{110,111}'

