stages:
  - test

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - $HOME/.cache/pip

before_script:
  - pip install tox

test_python36:
  stage: test
  image: python:3.6
  script: tox --skip-missing-interpreters
