stages:
  - test

cache:
  key: "$CI_PROJECT_NAME"
  paths:
    - $HOME/.cache/pip

before_script:
  - pip install tox

test_python36:
  stage: test
  image: python:3.6
  script: tox -e 'py36-django{111,200,210}'

test_pypy35:
  stage: test
  image: pypy:3-5
  script: tox -e 'pypy3-django{111,200,210}'
